package se.nackademin.stringify.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import se.nackademin.stringify.domain.ChatSession;

import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@ApiModel(description = "A chat session provided by the server")
public class ChatSessionDto implements IConvertEntity<ChatSession> {

    @ApiModelProperty(notes = "An id used by the client side and used for connecting chat session")
    private UUID guid;
    @ApiModelProperty(notes = "Key is generated by the server and is used for connecting to the chat session",
            example = "HY31A7")
    private String key;
    @ApiModelProperty(notes = "A shareable url to let others connect to the chat session",
            example = "https://stringify-chat.netlify.app/profile?connect=ed90421f-4ffe-4c7e-8110-f87ff00f69ba")
    private String connectUrl;
    @ApiModelProperty(notes = "CipherKey is used by the client side to encrypt and decrypt messages")
    private String cipherKey;

    @Builder
    public ChatSessionDto(
            UUID guid,
            String key,
            String connectUrl,
            String cipherKey) {
        this.guid = guid;
        this.key = key;
        this.connectUrl = connectUrl;
        this.cipherKey = cipherKey;
    }

    @Override
    public ChatSession convertToEntity() {
        return ChatSession.builder()
                .guid(this.guid)
                .key(this.key)
                .connectUrl(this.connectUrl)
                .build();
    }
}
